# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#
# ============================================================
# LUKS2 + BTRFS KURULUM ADIMLARI (yeni kurulum gerektirir)
# ============================================================
#
# 1. Bölümleme:
#    sgdisk -Z /dev/nvme0n1
#    sgdisk -n 1:0:+1G  -t 1:ef00 -c 1:"EFI"  /dev/nvme0n1
#    sgdisk -n 2:0:+8G  -t 2:8200 -c 2:"SWAP" /dev/nvme0n1
#    sgdisk -n 3:0:0    -t 3:8309 -c 3:"ROOT" /dev/nvme0n1
#
# 2. LUKS2 container:
#    cryptsetup luksFormat --type luks2 \
#      --cipher aes-xts-plain64 --key-size 512 \
#      --hash sha256 --pbkdf argon2id \
#      /dev/nvme0n1p3
#    cryptsetup open /dev/nvme0n1p3 cryptroot
#
# 3. UUID'leri al:
#    cryptsetup luksUUID /dev/nvme0n1p3   → LUKS-UUID
#    mkfs.btrfs -L nixos /dev/mapper/cryptroot
#    blkid /dev/mapper/cryptroot          → BTRFS-UUID
#    blkid /dev/nvme0n1p1                 → EFI-UUID
#    blkid /dev/nvme0n1p2                 → SWAP-UUID
#
# 4. Btrfs subvolume'ler:
#    mount /dev/mapper/cryptroot /mnt
#    for sv in @ @home @nix @log @snapshots; do
#      btrfs subvolume create /mnt/$sv; done
#    umount /mnt
#
# 5. UUID'leri aşağıya gir → nixos-install --flake /etc/nixos#nixos
# ============================================================

{ config, lib, pkgs, modulesPath, ... }:

let
  rootDev    = "/dev/disk/by-uuid/218ea50e-ef42-4dbb-ae3e-edefe43b6370";
  commonOpts = [ "noatime" "compress=zstd:1" "ssd" "space_cache=v2" "discard=async" ];
in

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [
    "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"
    "btrfs"
  ];
  boot.initrd.kernelModules = [ "dm-crypt" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # ============================================================
  # LUKS2 — şifreli container
  # allowDiscards : SSD TRIM'in LUKS içinden geçmesini sağlar
  # bypassWorkqueues: NVMe/SSD I/O gecikmesini azaltır
  # ============================================================
  boot.initrd.luks.devices."cryptroot" = {
    device           = "/dev/disk/by-uuid/038f2bb6-04c7-48c0-bb8d-0bb317f679f9";
    allowDiscards    = true;
    bypassWorkqueues = true;
  };

  # ============================================================
  # Btrfs subvolume'leri (/dev/mapper/cryptroot üzerinde)
  # ============================================================
  fileSystems."/" = {
    device  = rootDev;
    fsType  = "btrfs";
    options = commonOpts ++ [ "subvol=@" ];
  };

  fileSystems."/home" = {
    device  = rootDev;
    fsType  = "btrfs";
    options = commonOpts ++ [ "subvol=@home" ];
  };

  fileSystems."/nix" = {
    device  = rootDev;
    fsType  = "btrfs";
    # nodatacow: Nix store hardlink-ağırlıklı, CoW yazma amplifikasyonu yaratır
    options = [ "noatime" "nodatacow" "ssd" "space_cache=v2" "discard=async" "subvol=@nix" ];
  };

  fileSystems."/var/log" = {
    device        = rootDev;
    fsType        = "btrfs";
    options       = [ "noatime" "ssd" "space_cache=v2" "discard=async" "subvol=@log" ];
    neededForBoot = true;
  };

  fileSystems."/.snapshots" = {
    device  = rootDev;
    fsType  = "btrfs";
    options = commonOpts ++ [ "subvol=@snapshots" ];
  };

  fileSystems."/boot" = {
    device  = "/dev/disk/by-uuid/DBFB-317A";
    fsType  = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/0e0ee7ff-8ccf-41e0-a78f-651130ec2e2a";
        # priority=10: zramSwap (priority=100) her zaman önce kullanılır.
        # Bu partition yalnızca zram dolduğunda veya hibernasyon için devreye girer.
        priority = 10;
      } ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
